/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DateInput {
    }
}
declare global {
    interface HTMLDateInputElement extends Components.DateInput, HTMLStencilElement {
    }
    var HTMLDateInputElement: {
        prototype: HTMLDateInputElement;
        new (): HTMLDateInputElement;
    };
    interface HTMLElementTagNameMap {
        "date-input": HTMLDateInputElement;
    }
}
declare namespace LocalJSX {
    interface DateInput {
    }
    interface IntrinsicElements {
        "date-input": DateInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "date-input": LocalJSX.DateInput & JSXBase.HTMLAttributes<HTMLDateInputElement>;
        }
    }
}
